In [2]:
import pandas as pd
import numpy as np

In [2]:
results_set = pd.read_csv('results_llama.csv')
test_set = pd.read_csv('testset7-cleaned-JB-FFT.csv')

In [3]:
results_set.isna().sum()

Question    0
Answer      0
dtype: int64

In [4]:
test_set.isna().sum()

question          0
contexts          0
ground_truth      0
evolution_type    0
metadata          0
episode_done      0
dtype: int64

In [15]:
import re
# Define a function to extract context and answer using regular expressions
def extract_context_answer(text):
    match = re.search(r'CONTEXT:(.*?)QUESTION:(.*?)end_header_id(.*)$', text, re.DOTALL)
    if match:
        context = match.group(1).strip()
        answer = match.group(3).strip().replace("\n", " ").replace("\r", "").replace("|>", "")
        return context, answer
    else:
        return None, None

In [16]:
results_set[['context', 'answer']] = results_set['Answer'].apply(lambda x: pd.Series(extract_context_answer(x)))
results_set

,Question,Answer,context,answer
0,How did the overall quality of each Unit of A...,\n<|begin_of_text|><|start_header_id|>system<|...,NTU among universities to receive first-ever T...,What a great question! According to the late...
1,How does the growth of the digital economy im...,\n<|begin_of_text|><|start_header_id|>system<|...,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...
2,What are some characteristics of the undergra...,\n<|begin_of_text|><|start_header_id|>system<|...,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...
3,What are some examples of external businesses...,\n<|begin_of_text|><|start_header_id|>system<|...,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...
4,What are some examples of industrial placemen...,\n<|begin_of_text|><|start_header_id|>system<|...,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...
...,...,...,...,...
84,What job roles have graduates from the Departm...,\n<|begin_of_text|><|start_header_id|>system<|...,Careers in Computer Science\n\nThe industry-fo...,"Thank you for asking! As I mentioned earlier,..."
85,What job roles have recent Computer Science De...,\n<|begin_of_text|><|start_header_id|>system<|...,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...
86,Where's the top CS labs at NTU located?,\n<|begin_of_text|><|start_header_id|>system<|...,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...
87,Which NTU CS degree focuses on real-world skil...,\n<|begin_of_text|><|start_header_id|>system<|...,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...
88,Who holds the position of Deputy Head of Depar...,\n<|begin_of_text|><|start_header_id|>system<|...,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...

In [17]:
results_set["context"][0]

'NTU among universities to receive first-ever Turing Network Development Awards\n        \n            Wed 02 Feb 2022\n\nView all news\n\nOur events\n\n31\n                May\n            \n        \n        \n        \n            Sport Engineering Seminar Day 2024\n            \n                \n                \n                NTU Clifton Campus, \n                Teaching and Learning Building, \n                Clifton Lane, \n                Clifton, \n                Nottinghamshire, \n                \n                NG11 8NS\n\n18\n                Jun\n            \n        \n        \n        \n            Physical Activity and the Endocrine system 2024'

In [18]:
results_set = results_set.drop(columns=['Answer'])
results_set

,Question,context,answer
0,How did the overall quality of each Unit of A...,NTU among universities to receive first-ever T...,What a great question! According to the late...
1,How does the growth of the digital economy im...,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...
2,What are some characteristics of the undergra...,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...
3,What are some examples of external businesses...,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...
4,What are some examples of industrial placemen...,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...
...,...,...,...
84,What job roles have graduates from the Departm...,Careers in Computer Science\n\nThe industry-fo...,"Thank you for asking! As I mentioned earlier,..."
85,What job roles have recent Computer Science De...,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...
86,Where's the top CS labs at NTU located?,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...
87,Which NTU CS degree focuses on real-world skil...,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...
88,Who holds the position of Deputy Head of Depar...,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...

In [19]:
results_set = results_set.rename(columns={'Question': 'question'})
results_set

,question,context,answer
0,How did the overall quality of each Unit of A...,NTU among universities to receive first-ever T...,What a great question! According to the late...
1,How does the growth of the digital economy im...,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...
2,What are some characteristics of the undergra...,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...
3,What are some examples of external businesses...,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...
4,What are some examples of industrial placemen...,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...
...,...,...,...
84,What job roles have graduates from the Departm...,Careers in Computer Science\n\nThe industry-fo...,"Thank you for asking! As I mentioned earlier,..."
85,What job roles have recent Computer Science De...,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...
86,Where's the top CS labs at NTU located?,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...
87,Which NTU CS degree focuses on real-world skil...,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...
88,Who holds the position of Deputy Head of Depar...,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...

In [20]:
evaluation_set_LLaMa3 = pd.merge(results_set, test_set, on='question')
evaluation_set_LLaMa3

,question,context,answer,contexts,ground_truth,evolution_type,metadata,episode_done
0,How did the overall quality of each Unit of A...,NTU among universities to receive first-ever T...,What a great question! According to the late...,"[""Cyber Security Research Group (CSRG)\n ...",The overall quality of each Unit of Assessment...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
1,How does the growth of the digital economy im...,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...,['Home\n\nCourses\n\nComputer Science\n\nCompu...,The growth of the digital economy has signific...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
2,What are some characteristics of the undergra...,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...,['Home\n\nStudy\n\nAcademic Schools\n\nScience...,The undergraduate courses offered by the Depar...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
3,What are some examples of external businesses...,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...,['The strength and relevance of our teaching a...,Our department has over 200 industrial placeme...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
4,What are some examples of industrial placemen...,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...,['The strength and relevance of our teaching a...,Some examples of industrial placement partners...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
...,...,...,...,...,...,...,...,...
90,What job roles have graduates from the Departm...,Careers in Computer Science\n\nThe industry-fo...,"Thank you for asking! As I mentioned earlier,...","[""- BSc (Hons)\n\nAbout Computer Science\n\nFr...",Graduates from the Department of Computer Scie...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
91,What job roles have recent Computer Science De...,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...,"[""Careers in Computer Science\n\nThe industry-...",Recent Computer Science Department graduates f...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
92,Where's the top CS labs at NTU located?,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...,['Department of Computer Science\n Welc...,The top Computer Science (CS) labs at NTU are ...,reasoning,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
93,Which NTU CS degree focuses on real-world skil...,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...,['Home\n\nCourses\n\nComputer Science\n\nCompu...,"NTU's Computer Science courses, including the ...",multi_context,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
94,Who holds the position of Deputy Head of Depar...,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...,['Meet the team\n\nAhmad Lotfi\n \t ...,Joanna Hartley holds the position of Deputy He...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True

In [21]:
evaluation_set_LLaMa3.drop_duplicates(inplace=True)
evaluation_set_LLaMa3.dropna(inplace=True)
evaluation_set_LLaMa3

,question,context,answer,contexts,ground_truth,evolution_type,metadata,episode_done
0,How did the overall quality of each Unit of A...,NTU among universities to receive first-ever T...,What a great question! According to the late...,"[""Cyber Security Research Group (CSRG)\n ...",The overall quality of each Unit of Assessment...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
1,How does the growth of the digital economy im...,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...,['Home\n\nCourses\n\nComputer Science\n\nCompu...,The growth of the digital economy has signific...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
2,What are some characteristics of the undergra...,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...,['Home\n\nStudy\n\nAcademic Schools\n\nScience...,The undergraduate courses offered by the Depar...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
3,What are some examples of external businesses...,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...,['The strength and relevance of our teaching a...,Our department has over 200 industrial placeme...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
4,What are some examples of industrial placemen...,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...,['The strength and relevance of our teaching a...,Some examples of industrial placement partners...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True
...,...,...,...,...,...,...,...,...
90,What job roles have graduates from the Departm...,Careers in Computer Science\n\nThe industry-fo...,"Thank you for asking! As I mentioned earlier,...","[""- BSc (Hons)\n\nAbout Computer Science\n\nFr...",Graduates from the Department of Computer Scie...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
91,What job roles have recent Computer Science De...,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...,"[""Careers in Computer Science\n\nThe industry-...",Recent Computer Science Department graduates f...,simple,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
92,Where's the top CS labs at NTU located?,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...,['Department of Computer Science\n Welc...,The top Computer Science (CS) labs at NTU are ...,reasoning,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
93,Which NTU CS degree focuses on real-world skil...,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...,['Home\n\nCourses\n\nComputer Science\n\nCompu...,"NTU's Computer Science courses, including the ...",multi_context,[{'source': 'https://www.ntu.ac.uk/course/comp...,True
94,Who holds the position of Deputy Head of Depar...,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...,['Meet the team\n\nAhmad Lotfi\n \t ...,Joanna Hartley holds the position of Deputy He...,simple,[{'source': 'https://www.ntu.ac.uk/study-and-c...,True

In [22]:
evaluation_set_LLaMa3.to_csv('evaluation_set_LLaMa3.csv', index=False)

In [3]:
llama_inference = pd.read_csv("Llama_time.csv")
llama_inference

,Question,Answer,Time_Taken
0,How did the overall quality of each Unit of A...,\n<|begin_of_text|><|start_header_id|>system<|...,5.329553
1,How does the growth of the digital economy im...,\n<|begin_of_text|><|start_header_id|>system<|...,6.951586
2,What are some characteristics of the undergra...,\n<|begin_of_text|><|start_header_id|>system<|...,5.584647
3,What are some examples of external businesses...,\n<|begin_of_text|><|start_header_id|>system<|...,2.378410
4,What are some examples of industrial placemen...,\n<|begin_of_text|><|start_header_id|>system<|...,6.428545
...,...,...,...
84,What job roles have graduates from the Departm...,\n<|begin_of_text|><|start_header_id|>system<|...,7.074924
85,What job roles have recent Computer Science De...,\n<|begin_of_text|><|start_header_id|>system<|...,3.362952
86,Where's the top CS labs at NTU located?,\n<|begin_of_text|><|start_header_id|>system<|...,3.591490
87,Which NTU CS degree focuses on real-world skil...,\n<|begin_of_text|><|start_header_id|>system<|...,5.203300
88,Who holds the position of Deputy Head of Depar...,\n<|begin_of_text|><|start_header_id|>system<|...,1.006969

In [4]:
import re
# Define a function to extract context and answer using regular expressions
def extract_context_answer(text):
    match = re.search(r'CONTEXT:(.*?)QUESTION:(.*?)end_header_id(.*)$', text, re.DOTALL)
    if match:
        context = match.group(1).strip()
        answer = match.group(3).strip().replace("\n", " ").replace("\r", "").replace("|>", "")
        return context, answer
    else:
        return None, None

In [5]:
llama_inference[['context', 'answer']] = llama_inference['Answer'].apply(lambda x: pd.Series(extract_context_answer(x)))
llama_inference

,Question,Answer,Time_Taken,context,answer
0,How did the overall quality of each Unit of A...,\n<|begin_of_text|><|start_header_id|>system<|...,5.329553,NTU among universities to receive first-ever T...,What a great question! According to the lates...
1,How does the growth of the digital economy im...,\n<|begin_of_text|><|start_header_id|>system<|...,6.951586,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...
2,What are some characteristics of the undergra...,\n<|begin_of_text|><|start_header_id|>system<|...,5.584647,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...
3,What are some examples of external businesses...,\n<|begin_of_text|><|start_header_id|>system<|...,2.378410,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...
4,What are some examples of industrial placemen...,\n<|begin_of_text|><|start_header_id|>system<|...,6.428545,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...
...,...,...,...,...,...
84,What job roles have graduates from the Departm...,\n<|begin_of_text|><|start_header_id|>system<|...,7.074924,Careers in Computer Science\n\nThe industry-fo...,Thank you for asking! I'm happy to share with...
85,What job roles have recent Computer Science De...,\n<|begin_of_text|><|start_header_id|>system<|...,3.362952,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...
86,Where's the top CS labs at NTU located?,\n<|begin_of_text|><|start_header_id|>system<|...,3.591490,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...
87,Which NTU CS degree focuses on real-world skil...,\n<|begin_of_text|><|start_header_id|>system<|...,5.203300,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...
88,Who holds the position of Deputy Head of Depar...,\n<|begin_of_text|><|start_header_id|>system<|...,1.006969,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...

In [7]:
import nltk
from nltk import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /home/akash/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [8]:
# Function to count words in each row of the specified column
def count_words(answer):
    words = word_tokenize(answer)
    return len(words)

In [9]:
llama_inference['total_tokens'] = llama_inference['answer'].apply(count_words)
llama_inference

,Question,Answer,Time_Taken,context,answer,total_tokens
0,How did the overall quality of each Unit of A...,\n<|begin_of_text|><|start_header_id|>system<|...,5.329553,NTU among universities to receive first-ever T...,What a great question! According to the lates...,169
1,How does the growth of the digital economy im...,\n<|begin_of_text|><|start_header_id|>system<|...,6.951586,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...,256
2,What are some characteristics of the undergra...,\n<|begin_of_text|><|start_header_id|>system<|...,5.584647,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...,200
3,What are some examples of external businesses...,\n<|begin_of_text|><|start_header_id|>system<|...,2.378410,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...,75
4,What are some examples of industrial placemen...,\n<|begin_of_text|><|start_header_id|>system<|...,6.428545,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...,233
...,...,...,...,...,...,...
84,What job roles have graduates from the Departm...,\n<|begin_of_text|><|start_header_id|>system<|...,7.074924,Careers in Computer Science\n\nThe industry-fo...,Thank you for asking! I'm happy to share with...,260
85,What job roles have recent Computer Science De...,\n<|begin_of_text|><|start_header_id|>system<|...,3.362952,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...,113
86,Where's the top CS labs at NTU located?,\n<|begin_of_text|><|start_header_id|>system<|...,3.591490,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...,121
87,Which NTU CS degree focuses on real-world skil...,\n<|begin_of_text|><|start_header_id|>system<|...,5.203300,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...,194
88,Who holds the position of Deputy Head of Depar...,\n<|begin_of_text|><|start_header_id|>system<|...,1.006969,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...,30

In [11]:
llama_inference["tokens_per_second"] = llama_inference["total_tokens"] / llama_inference["Time_Taken"]
llama_inference

,Question,Answer,Time_Taken,context,answer,total_tokens,tokens_per_second
0,How did the overall quality of each Unit of A...,\n<|begin_of_text|><|start_header_id|>system<|...,5.329553,NTU among universities to receive first-ever T...,What a great question! According to the lates...,169,31.709976
1,How does the growth of the digital economy im...,\n<|begin_of_text|><|start_header_id|>system<|...,6.951586,Click for sound\n\n1:58\n\nPlay VideoHannah Ja...,What a great question! The growth of the dig...,256,36.826131
2,What are some characteristics of the undergra...,\n<|begin_of_text|><|start_header_id|>system<|...,5.584647,Home\n\nCourses\n\nComputer Science\n\nCompute...,Thank you for asking! The Department of Compu...,200,35.812468
3,What are some examples of external businesses...,\n<|begin_of_text|><|start_header_id|>system<|...,2.378410,The strength and relevance of our teaching and...,That's an easy one! Our department has establ...,75,31.533670
4,What are some examples of industrial placemen...,\n<|begin_of_text|><|start_header_id|>system<|...,6.428545,Course search\n\nOur students and alumni stori...,That's a great question! At Nottingham Trent ...,233,36.244593
...,...,...,...,...,...,...,...
84,What job roles have graduates from the Departm...,\n<|begin_of_text|><|start_header_id|>system<|...,7.074924,Careers in Computer Science\n\nThe industry-fo...,Thank you for asking! I'm happy to share with...,260,36.749513
85,What job roles have recent Computer Science De...,\n<|begin_of_text|><|start_header_id|>system<|...,3.362952,Careers in Computer Science\n\nThe industry-fo...,I'm happy to help! According to the informat...,113,33.601434
86,Where's the top CS labs at NTU located?,\n<|begin_of_text|><|start_header_id|>system<|...,3.591490,Software Engineer\n\nCyber Security Analyst\n\...,The top CS labs at NTU are located in our imp...,121,33.690750
87,Which NTU CS degree focuses on real-world skil...,\n<|begin_of_text|><|start_header_id|>system<|...,5.203300,Careers in Computer Science\n\nThe industry-fo...,That's an easy one! At Nottingham Trent Unive...,194,37.284035
88,Who holds the position of Deputy Head of Depar...,\n<|begin_of_text|><|start_header_id|>system<|...,1.006969,Meet the team\n\nAhmad Lotfi\n \t ...,That's an easy one! According to our lovely m...,30,29.792364

In [12]:
llama_inference.drop(['Answer', 'context'], axis=1, inplace=True)
llama_inference

,Question,Time_Taken,answer,total_tokens,tokens_per_second
0,How did the overall quality of each Unit of A...,5.329553,What a great question! According to the lates...,169,31.709976
1,How does the growth of the digital economy im...,6.951586,What a great question! The growth of the dig...,256,36.826131
2,What are some characteristics of the undergra...,5.584647,Thank you for asking! The Department of Compu...,200,35.812468
3,What are some examples of external businesses...,2.378410,That's an easy one! Our department has establ...,75,31.533670
4,What are some examples of industrial placemen...,6.428545,That's a great question! At Nottingham Trent ...,233,36.244593
...,...,...,...,...,...
84,What job roles have graduates from the Departm...,7.074924,Thank you for asking! I'm happy to share with...,260,36.749513
85,What job roles have recent Computer Science De...,3.362952,I'm happy to help! According to the informat...,113,33.601434
86,Where's the top CS labs at NTU located?,3.591490,The top CS labs at NTU are located in our imp...,121,33.690750
87,Which NTU CS degree focuses on real-world skil...,5.203300,That's an easy one! At Nottingham Trent Unive...,194,37.284035
88,Who holds the position of Deputy Head of Depar...,1.006969,That's an easy one! According to our lovely m...,30,29.792364

In [13]:
llama_inference.to_csv('llama_inference.csv', index=False)